[proxy_ru.domains]
donationalerts.com
ident.me

[proxy_ru.geosites]
2ch
ru-available-only-inside
tld-ru

[proxy_ru.geoips]
ru

[proxy_it.domains]
aeza.net
api.ipify.org
meduza.io
slickdeals.net

[proxy_it.geosites]
bestbuy
category-porn
rutracker
